
default:
  image: nbrei/jana2_env_everything_except_cuda

build-job-1:
  stage: build
  script:
    - echo "Running build job 1"

build-job-2:
  stage: build
  script:
    - echo "Running build job 2"

test-job-1:
  stage: test
  script:
    - echo "Running test job 1"
    - ./test_script.sh

deploy-job-1:
  stage: deploy
  script:
    - echo "Running deploy job 1"
